name: Other issue
description: Some problem not listed
title: "[Other] <subject>"
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the problem you're reporting.
    options:
    - label: I have searched for existing issues and did not find anything like it
      required: true
- type: textarea
  attributes:
    label: Describe the problem
    description: Please describe the issue that you are having.
  validations:
    required: true
- type: textarea
  attributes:
    label: What you expect
    description: Please describe what you think it should be instead and why.
  validations:
    required: true
- type: textarea
  attributes:
    label: Relevant links
    description: Please provide us with a list of relevant links if applicable.
  validations:
    required: false

- type: textarea
  attributes:
    label: Anything else?
    description: |
      Do you have any additional context or information?

      Tip: you can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

