name: sanity check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: clone mkiocccentry
      run: git clone https://github.com/ioccc-src/mkiocccentry
    - name: install jparse
    - run: cd mkiocccentry && make all && cd jparse && sudo make all install
    - name: remove mkiocccentry
    - run: rm -fr mkiocccentry
    - name: make test
      run: make test
